"""
Plot estimation error of inferred signal in compressed sensing 
from error objects (.npz) generated by calculate_errors.py, 
averaged over 2nd variables. 

Created by Nirag Kadakia at 22:00 10-25-2017
This work is licensed under the 
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 
International License. 
To view a copy of this license, visit 
http://creativecommons.org/licenses/by-nc-sa/4.0/.
"""


import scipy as sp
import sys
import matplotlib as mpl
import matplotlib.pyplot as plt
sys.path.append('../../shared_src')
from save_load_figure_data import load_success_ratios, load_binary_errors, \
									load_MSE_errors, load_odor_ID_errors, \
									save_fig
from plot_formats import fig_errors_vs_Kk

# The location of the source code for CS-variability-adaptation is listed
# in the ../../shared_src/local_methods file within src_dir()
from local_methods import src_dir
sys.path.append(src_dir())
from utils import get_flag
from load_specs import read_specs_file


def plot_errors_vs_Kk(data_flag, conc_shift=-4):
	"""
	Heatmap of errors as a function of background stimulus (x) and 
	odor complexity (y). conc_shift is shift of concentration to realistic 
	levels; i.e. consider all odor stimuli as relative to this value.
	"""
	
	list_dict = read_specs_file(data_flag)
	iter_vars = list_dict['iter_vars']
		
	assert len(iter_vars) == 3, "Need 3 iter_vars"
	iter_var = iter_vars.keys()[0]
	Kk_var = iter_vars.keys()[2]
	
	x = sp.log(iter_vars[iter_var])/sp.log(10) + conc_shift
	y = iter_vars[Kk_var]
	X, Y = sp.meshgrid(x, y)
	
	successes = load_success_ratios(data_flag)
	binary_errors = load_binary_errors(data_flag)
	errors_nonzero = binary_errors['errors_nonzero']
	errors_zero = binary_errors['errors_zero']
	
	# Plot successes, averaged over second axis of successes array
	fig = fig_errors_vs_Kk()
	avg_successes = sp.average(successes, axis=1)
	plt.pcolormesh(X, Y, avg_successes.T, cmap=plt.cm.hot, rasterized=True, 
					shading='gouraud', vmin=0, vmax=1)
	plt.xlim(-4, 0)
	plt.ylim(1, 7)
	save_fig('errors_vs_Kk', subdir=data_flag)
	
	fig = plt.figure()
	fig.set_size_inches(1, 5)
	ax1 = fig.add_axes([0.1, 0.1, 0.3, 0.7])
	norm = mpl.colors.Normalize(vmin=0, vmax=100)
	cbar = mpl.colorbar.ColorbarBase(ax1, cmap=plt.cm.hot,
                                norm=norm, ticks=[0, 50, 100],
                                orientation='vertical')
	cbar.ax.tick_params(labelsize=25)
	save_fig('errors_vs_Kk_colorbar', subdir=data_flag, tight_layout=False)
	
	
if __name__ == '__main__':
	data_flag = get_flag()
	plot_errors_vs_Kk(data_flag)